In [9]:
import numpy as np;

arr_int = [1,5,6,20]
arr_int = np.array(arr_int)
arr_int

array([ 1,  5,  6, 20])

In [14]:
# number of dimensions
print(arr_int.ndim)

# shape
print(arr_int.shape)

# size
print(arr_int.size)

# dtype
print(arr_int.dtype)

# type
print(type(arr_int))

# type conversion
print(arr_int.tolist())

1
(4,)
4
int32
<class 'numpy.ndarray'>
[1, 5, 6, 20]


In [20]:
arr_mix = np.array([[1, 2, 3.0], [4, 5, 6], (7, 8, 9)])
print(arr_mix)

# dtype
print(arr_mix.dtype)

# shape
print(arr_mix.shape)

# dimensions
print(arr_mix.ndim) 

# size  
print(arr_mix.size)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64
(3, 3)
2
9


In [30]:
arr_str = np.array(["a", "b", 1])
arr_str

array(['a', 'b', '1'], dtype='<U11')

### Creating NumPy array using arange(), linspace() and random() functions

In [24]:
# 10 is exclusive 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# end is exclusive
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
np.linspace(0, 10, 7, dtype=int)

array([ 0,  1,  3,  5,  6,  8, 10])

In [36]:
# if endpoint is not included, use endpoint=false
np.linspace(0, 10, 7, dtype=int, endpoint=False)

array([0, 1, 2, 4, 5, 7, 8])

In [40]:
# 1-dim array
np.random.rand(10)

array([0.95280614, 0.05910838, 0.22239914, 0.81015528, 0.97842231,
       0.55869732, 0.4802614 , 0.84027585, 0.61369245, 0.29264213])

In [41]:
# 2-dim array
np.random.rand(3, 3)

array([[0.31514847, 0.49437097, 0.61009149],
       [0.88641371, 0.66861522, 0.49693125],
       [0.98878792, 0.04951731, 0.89137842]])

In [53]:
# generate random float 0 to 1
np.random.rand()

array([9.59174778e-01, 9.54764151e-01, 5.09261086e-01, 5.46802286e-04,
       5.92726183e-01, 4.56799640e-01, 1.28504607e-02, 7.66660325e-01,
       6.35140482e-01, 9.33073457e-01])

In [54]:
# generate random integer 0 to 9
np.random.randint(10)

1

In [47]:
# generate 1-dim array of 4 random integers
np.random.randint(10, size=4)

array([1, 5, 6, 0])

In [55]:
# generate 2-dim array of 3 x 3 random integers
np.random.randint(10, size=(3, 3))

array([[3, 8, 4],
       [8, 4, 3],
       [0, 7, 3]])

### Creating NumPy arrays of 1s and 0s

In [62]:
arr_zeros = np.zeros((4,1), dtype=int)
arr_zeros

array([[0],
       [0],
       [0],
       [0]])

In [63]:
# shape
arr_zeros.shape

(4, 1)

In [74]:
arr_3dim = np.ones((2, 2, 2), dtype=int)
arr_3dim

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [83]:
# type casting using astype
arr_int = arr_int.astype(np.float64)
arr_int

array([ 1.,  5.,  6., 20.])

### Operations with numpy array


In [85]:
arr_int = np.array(np.arange(0,10))
arr_int

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# multiply by 2
arr_int * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
# add by 3
arr_int + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
# power by 2
arr_int ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Arithmetic operations with numpy arrays

In [90]:
array1 = np.array([[5, 4, 6, 1], [2, 3, 8, 10]])
array2 = np.array([[10, 12, 5, 17], [22, 33, 88, 100]])
print(array1)
print(array2)

[[ 5  4  6  1]
 [ 2  3  8 10]]
[[ 10  12   5  17]
 [ 22  33  88 100]]


In [93]:
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 // array2)
print(array1 % array2)
print(array1 ** array2)

[[ 15  16  11  18]
 [ 24  36  96 110]]
[[ -5  -8   1 -16]
 [-20 -30 -80 -90]]
[[  50   48   30   17]
 [  44   99  704 1000]]
[[0.5        0.33333333 1.2        0.05882353]
 [0.09090909 0.09090909 0.09090909 0.1       ]]
[[0 0 1 0]
 [0 0 0 0]]
[[ 5  4  1  1]
 [ 2  3  8 10]]
[[    9765625    16777216        7776           1]
 [    4194304 -1504003197           0           0]]


In [94]:
print(np.add(array1, array2))
print(np.subtract(array1, array2))
print(np.multiply(array1, array2))
print(np.divide(array1, array2))
print(np.floor_divide(array1, array2))
print(np.mod(array1, array2))
print(np.power(array1, array2))

[[ 15  16  11  18]
 [ 24  36  96 110]]
[[ -5  -8   1 -16]
 [-20 -30 -80 -90]]
[[  50   48   30   17]
 [  44   99  704 1000]]
[[0.5        0.33333333 1.2        0.05882353]
 [0.09090909 0.09090909 0.09090909 0.1       ]]
[[0 0 1 0]
 [0 0 0 0]]
[[ 5  4  1  1]
 [ 2  3  8 10]]
[[    9765625    16777216        7776           1]
 [    4194304 -1504003197           0           0]]


In [105]:
array4 = np.array([2,3,4])
array5 = np.array([[1,3],[2,3]])
result = array5 + array4
result

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [137]:
x = np.ones((2, 2))
y = np.zeros((3)) + 2
print(x , y)
x + y

[[1. 1.]
 [1. 1.]] [2. 2. 2.]


ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [141]:
array1 = np.array([[5, 4, 6, 1], [2, 3, 8, 10]])
array2 = np.array([[0., 4., 1., 12.], [7., 2., 35, 4]])
array1 > array2

array([[ True, False,  True, False],
       [False,  True, False,  True]])

In [149]:
array2[1:,:1]

array([[7.]])

In [152]:
array3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array3[:4]

array([1, 2, 3, 4])