In [1]:
import numpy as np
import time
from PIL import Image

# 1. Basics: Arrays and Properties
# Create a 5x5 array with 7 on the border and 0 inside
arr = np.ones((5,5)) * 7
arr[1:-1, 1:-1] = 0
print('1. Basics:')
print(arr)

# 2. Indexing and Slicing
arr = np.arange(1, 21).reshape(4, 5)
print('2. Indexing and Slicing - Original:')
print(arr)

# Extract even numbers
even_nums = arr[arr % 2 == 0]
print('Even numbers:')
print(even_nums)

# Replace elements divisible by 3 with -1
arr[arr % 3 == 0] = -1
print('Modified:')
print(arr)

# 3. Array Manipulation
a = np.arange(100).reshape(10,10)
print('3. Array Manipulation - Diagonal:', np.diag(a))
print('Anti-diagonal:', np.fliplr(a).diagonal())

# 4. Stacking and Splitting
a = np.ones((2, 3))
b = np.zeros((2, 3))

v_stacked = np.vstack((a, b))
h_stacked = np.hstack((a, b))

print('4. Stacking and Splitting - Vertical:')
print(v_stacked)
print('Horizontal:')
print(h_stacked)

split_array = np.hsplit(h_stacked, 2)
print('Split Result:')
print(split_array)

# 5. Mathematical Operations
scores = np.array([[80, 90, 70],
                   [60, 85, 75],
                   [95, 88, 92]])

# Average per student (row)
print('5. Mathematical Operations - Student Averages:', scores.mean(axis=1))

# Average per subject (column)
print('Subject Averages:', scores.mean(axis=0))

# 6. Broadcasting
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Subtract row-wise mean
row_mean = a.mean(axis=1, keepdims=True)
normalized = a - row_mean
print('6. Broadcasting - Normalized:')
print(normalized)

# 7. Random Number Generation
np.random.seed(42)
tosses = np.random.randint(0, 2, 1000)
heads = np.sum(tosses == 1)
print('7. Random Number Generation - Heads count:', heads)

# 8. Set Operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7])

print('8. Set Operations - Common:', np.intersect1d(a, b))
print('Unique to a:', np.setdiff1d(a, b))
print('Union:', np.union1d(a, b))

# 9. Linear Algebra
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print('9. Linear Algebra - Solution:', x)

# 10. Missing Data
data = np.array([[1, 2, np.nan],
                 [4, np.nan, 6],
                 [7, 8, 9]])

# Replace NaN with column mean
col_mean = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_mean, inds[1])
print('10. Missing Data:')
print(data)

# 11. Advanced Indexing
arr = np.random.randint(0, 100, size=(5, 5))
print('11. Advanced Indexing - Array:')
print(arr)

print('Min Value:', arr.min(), 'at', np.unravel_index(arr.argmin(), arr.shape))
print('Max Value:', arr.max(), 'at', np.unravel_index(arr.argmax(), arr.shape))

# 12. Sorting and Searching
arr = np.array([[1, 3],
                [7, 2],
                [5, 9]])

# Sort by second column
sorted_arr = arr[arr[:, 1].argsort()]
print('12. Sorting and Searching:')
print(sorted_arr)

# 13. Custom Functions + Vectorization
def classify(x):
    if x < 0:
        return 'Negative'
    elif x == 0:
        return 'Zero'
    else:
        return 'Positive'

vec_classify = np.vectorize(classify)
data = np.array([-3, 0, 5, 2, -1])
print('13. Custom Functions + Vectorization:')
print(vec_classify(data))

# 14. Performance
data = np.random.rand(1000000)

# Loop
start = time.time()
count = 0
for i in data:
    if i > 0.5:
        count += 1
end = time.time()
print('14. Performance - Loop:', count, 'Time:', end - start)

# Vectorized
start = time.time()
count_vec = np.sum(data > 0.5)
end = time.time()
print('Vectorized:', count_vec, 'Time:', end - start)

# Bonus Mini-Project (Image Grayscale)
# You will need to replace 'your_image.jpg' with an actual image file path
img = Image.open('your_image.jpg')
img_np = np.array(img)

# Convert to grayscale
gray = np.dot(img_np[...,:3], [0.2989, 0.5870, 0.1140])
Image.fromarray(gray.astype(np.uint8)).show()

1. Basics:
[[7. 7. 7. 7. 7.]
 [7. 0. 0. 0. 7.]
 [7. 0. 0. 0. 7.]
 [7. 0. 0. 0. 7.]
 [7. 7. 7. 7. 7.]]
2. Indexing and Slicing - Original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Even numbers:
[ 2  4  6  8 10 12 14 16 18 20]
Modified:
[[ 1  2 -1  4  5]
 [-1  7  8 -1 10]
 [11 -1 13 14 -1]
 [16 17 -1 19 20]]
3. Array Manipulation - Diagonal: [ 0 11 22 33 44 55 66 77 88 99]
Anti-diagonal: [ 9 18 27 36 45 54 63 72 81 90]
4. Stacking and Splitting - Vertical:
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Horizontal:
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
Split Result:
[array([[1., 1., 1.],
       [1., 1., 1.]]), array([[0., 0., 0.],
       [0., 0., 0.]])]
5. Mathematical Operations - Student Averages: [80.         73.33333333 91.66666667]
Subject Averages: [78.33333333 87.66666667 79.        ]
6. Broadcasting - Normalized:
[[-1.  0.  1.]
 [-1.  0.  1.]]
7. Random Number Generation - Heads count: 510
8. Set Operations - Common: [4 5]
Unique to a: [1 2 3

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Drashti Trivedi\\Documents\\Data Science\\your_image.jpg'

In [3]:
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))
# np.hstack((a, b))


array([[1, 2],
       [3, 4]])

In [9]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
checkboard = np.zeros((8,8), dtype=int)
checkboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
checkboard[1::2,::2] = 1
checkboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [35]:
checkboard[::2, 1::2] = 1
checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [42]:
arr = np.array([1,2,3,4,2,1,2,4])
counts = np.bincount(arr)
counts

array([0, 2, 3, 1, 2], dtype=int64)

In [43]:
most_freq = np.argmax(counts)
most_freq

2

In [70]:
arr = np.zeros((5,5), dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [74]:
arr[0, :] = 1
arr[:,0] = 1
arr[-1,:] = 1
arr[:, -1] = 1
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [75]:
arr = np.zeros((5,5), dtype=int)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
print(np.pad(arr, pad_width=1, mode='constant', constant_values=1)) 


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
