# Numpy Basics

In [1]:
import numpy as np

arr = np.array([0,1, 2, 3, 4, 5])
print(arr)
np.__version__


[0 1 2 3 4 5]


'1.26.4'

In [2]:
oned_arr = np.array([1, 2, 3, 4, 5, 6])
print(oned_arr)

twod_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(twod_arr)

twod_arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod_arr1)

threed_arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(threed_arr)

threed_arr1 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(threed_arr1)

dim_arr = np.array([1,2,3,4,5], ndmin = 5)
print(dim_arr)

dim_arr1 = np.array([1,2,3,4,5], ndmin = 6)
print(dim_arr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[[[1 2 3 4 5]]]]]
[[[[[[1 2 3 4 5]]]]]]


## numpy data types

1. i - integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
9. S - string
10. U - unicode string
11. V - fixed chunk of memory for other type ( void )

## checking the data type of an array  - arr.dtype

In [3]:
print(arr.dtype)

s_arr = np.array([1,2,3,4,5], dtype= "S")
print(s_arr)
print(s_arr.dtype)

i4_arr = np.array([1, 2, 3, 4], dtype='i4')

print(i4_arr)
print(i4_arr.dtype)

# A non integer string like 'a' can not be converted to integer (will raise an error):
# si4_arr = np.array(['a', 'b', 'c', 'd'], dtype='i4')
# print(si4_arr)


int32
[b'1' b'2' b'3' b'4' b'5']
|S1
[1 2 3 4]
int32


## astype() - change the data type of an existing array, is to make a copy of the array with the astype() method.

In [4]:
newi4_arr = i4_arr.astype('f') # integer to float
print( newi4_arr)
print(newi4_arr.dtype)

f_arr = np.array([1.1, 2.2, 3.1, 4,2])
print(f_arr)
print(f_arr.dtype)

newf_arr = f_arr.astype('i') # float to integer using astype(int) too
print(newf_arr)    
print(newf_arr.dtype)

bool_arr = arr.astype(bool) # integer to boolean
print(bool_arr)
print(bool_arr.dtype)


[1. 2. 3. 4.]
float32
[1.1 2.2 3.1 4.  2. ]
float64
[1 2 3 4 2]
int32
[False  True  True  True  True  True]
bool


## numpy copy vs view

### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [5]:
copy_arr = np.copy(arr)
print(copy_arr)

# changes in copy_arr will not reflect in arr
copy_arr[5] = 6
print(copy_arr)
print(arr)

# changes in arr will reflect in copy_arr
arr[5] = 7
print(arr)
print(copy_arr)

[0 1 2 3 4 5]
[0 1 2 3 4 6]
[0 1 2 3 4 5]
[0 1 2 3 4 7]
[0 1 2 3 4 6]


In [6]:
view_arr = arr.view()
print(view_arr)

# changes in view_arr will reflect in arr
view_arr[5] = 6
print(view_arr)
print(arr)

# changes in arr will reflect in view_arr
arr[5] = 7
print(arr)
print(view_arr)


[0 1 2 3 4 7]
[0 1 2 3 4 6]
[0 1 2 3 4 6]
[0 1 2 3 4 7]
[0 1 2 3 4 7]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [7]:
print(copy_arr.base) # None as it is a copy and owns the data
print(view_arr.base)  # arr as it is a view and does not own the data

None
[0 1 2 3 4 7]


## numpy array shape

In [8]:
print(arr.shape) # (6,) as it is a 1D array

print(twod_arr.shape) # (2, 3) as it is a 2D array

print(twod_arr1.shape) # (3, 3) as it is a 2D array

print(threed_arr.shape) # (2, 3, 3) as it is a 3D array

print(threed_arr1.shape) # (3, 3, 3) as it is a 3D array

print(dim_arr.shape) # (1, 1, 1, 1, 5) as it is a 5D array

print(dim_arr1.shape) # (1, 1, 1, 1, 1, 5) as it is a 6D array

(6,)
(2, 3)
(3, 3)
(2, 3, 3)
(3, 3, 3)
(1, 1, 1, 1, 5)
(1, 1, 1, 1, 1, 5)


## numpy array reshaping

In [9]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

# from 1-d to 2-d 
newarr1 = arr1.reshape(2,3)
print(newarr1)

# newarr2 = arr1.reshape(2,2)
# print(newarr2)

# 3 arrays with 2 elements
newarr3 = arr1.reshape(3,2) # 1D to 2D
print(newarr3)

# 6 arrays with 1 element
newarr4 = arr1.reshape(6,1) # 1D to +2D
print(newarr4)

# 1 array with 6 elements
newarr5 = arr1.reshape(1,6)  # 1D to 2D
print(newarr5)

# 3 arrays then 2 arrays with 1 element
newarr6 = arr1.reshape(3,2,1)  # 1D to 3D
print(newarr6)

# 1 array then 3 arrays with 2 elements
newarr7 = arr1.reshape(1,3,2)  # 1D to 3D 
print(newarr7)

# 2 arrays then 1 array with 1 element
newarr8 = arr1.reshape(2,3,1)  # 1D to 3D
print(newarr8)

# 1 array then 2 arrays with 1 element
newarr9 = arr1.reshape(2,1,3)  # 1D to 3D
print(newarr9)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
[[[1 2]
  [3 4]
  [5 6]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[1 2 3]]

 [[4 5 6]]]


In [10]:
# check if the return array is a copy or a view

print(newarr1.base) # [1,2 ,3, 4, 5, 6] as it is a view and owns the data
newarr1[0][1] = 11
print(arr1)
print(newarr1)

arr1[0] = 10
print(arr1)
print(newarr1)

[1 2 3 4 5 6]
[ 1 11  3  4  5  6]
[[ 1 11  3]
 [ 4  5  6]]
[10 11  3  4  5  6]
[[10 11  3]
 [ 4  5  6]]


In [11]:
# unknown dimension 

print(arr)

# unknown dimension with 2d
un_arr = arr.reshape(2, -1)
print(un_arr)

un_arr1 = arr.reshape(3, -1)
print(un_arr1)

un_arr4 = arr.reshape(6, -1)
print(un_arr4)

# unknown dimension with 3d
un_arr5 = arr.reshape(2, 3, -1)
print(un_arr5)

un_arr6 = arr.reshape(3, 2, -1)
print(un_arr6)


[0 1 2 3 4 7]
[[0 1 2]
 [3 4 7]]
[[0 1]
 [2 3]
 [4 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [7]]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [7]]]
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [7]]]


In [12]:
# Flattening the arrays with reshape
flat_arr = np.array([[1, 2, 3], [4, 5, 6]])

newflat_arr = flat_arr.reshape(-1)
print(newflat_arr)

# Flattening the arrays with ravel
flat_arr1 = np.array([[1, 2, 3], [4, 5, 6]])

newflat_arr1 = flat_arr1.ravel()
print(newflat_arr1)

# Flattening the arrays with flatten
flat_arr2 = np.array([[1, 2, 3], [4, 5, 6]])

newflat_arr2 = flat_arr2.flatten()
print(newflat_arr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


## numpy array iterating

In [13]:
# iterating 1D array

arr1 = np.array([1, 2, 3, 4, 5, 6])
for i in arr1:
    print(i)
    
# iterating 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for i in arr2:
    print(i)
    
for i in arr2:
    for j in i:
        print(j)
        
# iterating 3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
for i in arr3:
    #print(i)
    for j in i:
        # print(j)
        for k in j:
            print(k)
            
# iterating 4D array
arr4 = np.array([[[[1,2,3],[4, 5, 6]],[[1,2,3],[4,5,6]]]])
# print(arr4)
for i in arr4:
    # print(i)
    for j in i:
        # print(j)  
        for k in j:
            # print(k)
            for l in k:
                print(l)
    

1
2
3
4
5
6
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
1
2
3
4
5
6


## Iterating Arrays Using nditer()

In [14]:
print(arr2)
for i in np.nditer(arr2):
    print(i)
    
# same for 3D array
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


In [15]:
# iterate through the array as string
for i in np.nditer(arr2, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [16]:
# Iterating With Different Step Size
for x in np.nditer(arr2[:, ::2]):   #select all rows and every second column starting with 0
    print(x)
    
for x in np.nditer(arr2[::2]): #select every 2 row starting with 0
    print(x)

1
3
4
6
1
2
3


In [17]:
# ndemunerate
for i, x in np.ndenumerate(arr):
    print(i, x)
    
for i, x in np.ndenumerate(arr2):
    print(i, x)
    
for i, x in np.ndenumerate(arr3):
    print(i, x)
    
for i, x in np.ndenumerate(arr4):
    print(i, x)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 7
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6
(1, 2, 0) 7
(1, 2, 1) 8
(1, 2, 2) 9
(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3
(0, 0, 1, 0) 4
(0, 0, 1, 1) 5
(0, 0, 1, 2) 6
(0, 1, 0, 0) 1
(0, 1, 0, 1) 2
(0, 1, 0, 2) 3
(0, 1, 1, 0) 4
(0, 1, 1, 1) 5
(0, 1, 1, 2) 6


## joining numpy arrays

In [18]:
# concatenating arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2])
print(arr3)

arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr5 = np.array([[7, 8, 9], [10, 11, 12]])
arr6 = np.concatenate([arr4, arr5])
print(arr6)

arr7 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr8 = np.array([[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]])
arr9 = np.concatenate([arr7, arr8])
print(arr9)



[1 2 3 4 5 6]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


In [19]:
# using stack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.stack([arr1, arr2])
print(arr3)

arr4 = np.stack([arr1, arr2], axis=1)
print(arr4)



[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
arr5 = np.hstack([arr1, arr2]) # horizontally
print(arr5)

arr6 = np.vstack([arr1, arr2])  # vertically
print(arr6)

arr7 = np.dstack([arr1, arr2])  # depth
print(arr7)

print(np.vstack(([[1,2], [3,4]], [[5,6], [7,8]])))
print(np.hstack(([[1,2], [3,4]], [[5,6], [7,8]])))
print(np.dstack(([[1,2], [3,4]], [[5,6], [7,8]])))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [21]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

result = np.stack((a, b, c), axis=1)
print(result)

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[5, 6, 7], [8, 9, 10]])

result = np.hstack((a, b))
print(result)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.hstack((a, b))
print(result)

result = np.dstack((a, b))
print(result)


[[1 3 5]
 [2 4 6]]
[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=1))


[[1 4]
 [2 5]
 [3 6]]


In [23]:
a = np.array([[1, 2]])
b = np.array([3, 4])

result = np.vstack((a, b)) 
print(result)

[[1 2]
 [3 4]]


In [24]:
a = np.ones((2, 3))
b = np.zeros((2, 3))

stacked = np.stack((a, b), axis=0)
print(stacked)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
r = np.full((2, 2), 255)
g = np.ones((2, 2))
b = np.zeros((2, 2))
print(r)

[[255 255]
 [255 255]]


In [26]:
print(np.stack((r, g, b), axis=0))

[[[255. 255.]
  [255. 255.]]

 [[  1.   1.]
  [  1.   1.]]

 [[  0.   0.]
  [  0.   0.]]]


In [27]:
print(np.stack((r, g, b), axis=1))

[[[255. 255.]
  [  1.   1.]
  [  0.   0.]]

 [[255. 255.]
  [  1.   1.]
  [  0.   0.]]]


In [28]:
print(np.stack((r, g, b), axis=2))

[[[255.   1.   0.]
  [255.   1.   0.]]

 [[255.   1.   0.]
  [255.   1.   0.]]]


## numpy array splits

In [29]:
# split 1D array

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,4)
print(newarr)

newarr1 = np.array_split(arr,3)
print(newarr1)
print(newarr1[0])
print(newarr1[1])
print(newarr1[2])

newarr2 = np.array_split(arr,2)
print(newarr2)

newarr3 = np.array_split(arr,6)
print(newarr3)

newarr4 = np.array_split(arr,7)
print(newarr4)

newarr5 = np.array_split(arr,8)
print(newarr5)

print(np.array_split(arr, 2, axis=0))


[array([1, 2]), array([3, 4]), array([5]), array([6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]
[array([1, 2, 3]), array([4, 5, 6])]


In [30]:
# split 2D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr,2)
print(newarr)

newarr1 = np.array_split(arr,3)
print(newarr1)
print(newarr1[0])   
print(newarr1[1])
print(newarr1[2])

newarr2 = np.array_split(arr,4)
print(newarr2)

newarr3 = np.array_split(arr,5)
print(newarr3)

newarr4 = np.array_split(arr,6)
print(newarr4)

newarr5 = np.array_split(arr,7)
print(newarr5)


[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]]), array([], shape=(0, 3), dtype=int32)]


In [31]:
newarr8 = np.array_split(arr,3, axis=1)
print(newarr8)

newarr9 = np.array_split(arr,3, axis=0)
print(newarr9)

newarr10 = np.array_split(arr,4, axis=1)
print(newarr10)



[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [32]:
newarr11 = np.hsplit(arr,3)
print(newarr11)

newarr12 = np.vsplit(arr,3)
print(newarr12)

oned_arr = np.array([1, 2, 3, 4, 5, 6])
print(np.array_split(oned_arr, 6))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


## Searching arrays

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.where(arr == 5)
print(x)

# arr = np.array([1, 2, 3, 4, 5, 4, 4])
# x = np.where(arr == 4)
# print(x)

y = np.where(arr % 2 == 0)
print(y)

x1 = np.where(arr > 5)
print(x1)

x2 = np.where(arr < 5)
print(x2)

(array([4], dtype=int64),)
(array([1, 3, 5], dtype=int64),)
(array([5], dtype=int64),)
(array([0, 1, 2, 3], dtype=int64),)


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.searchsorted(arr, 4)
print(x)

x1 = np.searchsorted(arr, 4, side='right')
print(x1)


3
4


## numpy sort


In [35]:
# This method returns a copy of the array, leaving the original array unchanged.
arr = np.array([3,2,0,1])
sorted_arr = np.sort(arr)
print(sorted_arr)

print(arr.argsort())

# 2d array
arr = np.array([[3,2,0,1], [6,4,2,1]])
sorted_arr = np.sort(arr)
print(sorted_arr)
print(arr.argsort())


[0 1 2 3]
[2 3 1 0]
[[0 1 2 3]
 [1 2 4 6]]
[[2 3 1 0]
 [3 2 1 0]]


In [36]:
print(np.sort([[3,1], [2,4]], axis=0))

[[2 1]
 [3 4]]


In [37]:
print(np.sort([[3,1], [2,4]], axis=1))

[[1 3]
 [2 4]]


In [38]:
print(np.sort([[3,1,0], [2,4,1]], axis=0))

[[2 1 0]
 [3 4 1]]


In [39]:
print(np.sort([[3,1,0], [2,4,1]], axis=1))

[[0 1 3]
 [1 2 4]]


## numpy filter

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [40]:
arr = np.array([3,2,0,1])
x = [True, False, True, False]
filtered_arr = arr[x]
print(filtered_arr)

[3 0]


In [41]:
arr = np.array([12,45,34,67,89,90])
filtered_arr = []

for i in arr:
    if i % 2 == 0:
        filtered_arr.append(True)
    else:
        filtered_arr.append(False)

newarr = arr[filtered_arr]
print(newarr)

[12 34 90]


In [42]:
filtered_arr = arr % 2 == 0
newarr = arr[filtered_arr]
print(newarr)

[12 34 90]


## numpy random

In [43]:
import random

# generate int
x = random.randint(1, 100)
print(x)

# generate float from 0 to 1
y = np.random.rand()
print(y)

# generate float from 0 to 100
z = random.uniform(0, 100)
print(z)

# generate arr int
arr = np.random.randint(1, 100, 5)
print(arr)

# generate floatarray
arr = np.random.rand(5)
print(arr)

# generate 2d array
arr1 = np.random.randint(1,100,(3, 5))
print(arr1)

# generate 3d array
arr3 = np.random.rand(2, 3, 4)
print(arr3)

42
0.4229350713231652
1.756091139420568
[61 11 57 32  2]
[0.87613612 0.75913926 0.26978238 0.46197563 0.57015415]
[[ 7 62 38 29 63]
 [82 85 53 44 20]
 [12 21 61 16 39]]
[[[0.50597028 0.68386394 0.49228709 0.05259132]
  [0.5470814  0.38222974 0.34974814 0.64546034]
  [0.3869738  0.80974091 0.46530547 0.86313135]]

 [[0.09043703 0.92381584 0.86363    0.10980416]
  [0.34412148 0.34142313 0.2835529  0.98044123]
  [0.13011674 0.08977873 0.6968861  0.46063452]]]


In [44]:
# choice allows you to generate random values from a list

y = np.random.choice([3, 5, 7, 9])
print(y)

7


In [45]:
# generate 4d array
arr4 = np.random.randint(1, 100,(2,3,2,1))
print(arr4)

[[[[ 2]
   [63]]

  [[ 1]
   [51]]

  [[68]
   [26]]]


 [[[26]
   [ 2]]

  [[75]
   [50]]

  [[ 6]
   [ 7]]]]


## arrange()

In [46]:
# arange - (start, stop, step) - stop is exclusive
arr = np.arange(10)
print(arr)

arr1 = np.arange(1, 10)
print(arr1)

arr2 = np.arange(1, 10, 2)
print(arr2)

arr3 = np.arange(1, 10, 3)
print(arr3)

arr4 = np.arange(10, 1, -1)
print(arr4)

arr5 = np.arange(10, 1, -2)
print(arr5)

print(np.arange(1, 10, dtype=float))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 4 7]
[10  9  8  7  6  5  4  3  2]
[10  8  6  4  2]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


## linspace(start, stop, number of elements)

In [47]:
print(np.linspace(1, 10, 5))
print(np.linspace(1,10, 10, dtype=int))
print(np.linspace(1, 10, 6,dtype=int, endpoint=False))

[ 1.    3.25  5.5   7.75 10.  ]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 4 5 7 8]


## zeros()

In [48]:
print(np.zeros(5))
print(np.zeros(10, dtype=int))
print(np.zeros((2,3), dtype=int))
print(np.zeros((2,3,4), dtype=int))
print(np.zeros((2,2,3,4,1), dtype=int))

[0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[[[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]]


  [[[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]]]



 [[[[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]]


  [[[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]

   [[0]
    [0]
    [0]
    [0]]]]]


## ones()

In [49]:
print(np.ones(5, dtype=int))
print(np.ones((2,3,4), dtype=int))

[1 1 1 1 1]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


## create an empty array

In [50]:
print(np.empty(5, dtype=int))
print(np.empty((2,3,4), dtype=int))
print(np.empty(10))

[1 1 1 1 1]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


## oprations on array   

In [51]:
# operations on 1d array    
arr = np.array([1, 2, 3, 4, 5])
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)
print(arr // 5)
print(arr % 5)
print(arr ** 5)
print(arr > 5)
print(arr < 5)
print(arr >= 5)
print(arr <= 5)
print(arr == 5)
print(arr != 5)

[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[0 0 0 0 1]
[1 2 3 4 0]
[   1   32  243 1024 3125]
[False False False False False]
[ True  True  True  True False]
[False False False False  True]
[ True  True  True  True  True]
[False False False False  True]
[ True  True  True  True False]


## broadcasting

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [53]:
a = np.array([10,10,10])
b = np.array([[1, 2, 3], [4, 5, 6]])
print(a + b)

[[11 12 13]
 [14 15 16]]


In [54]:
a = np.array([[1], [2], [3]])
b = np.array([10,20,30])
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [55]:
a = np.ones((2,3,4), dtype=int)
print(a)
b = np.arange(4)
print(b)
print(a + b)
print(b + a)


[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[0 1 2 3]
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [56]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
B = np.array([10, 20, 30])            # Shape (3,)

result = A + B
print(result)

[[11 22 33]
 [14 25 36]]


In [57]:
a = np.array([[1,2], [3,4], [5,6]])
b = np.array([[2,2]])
print(a.shape, b.shape)
c = a + b
print(c)

(3, 2) (1, 2)
[[3 4]
 [5 6]
 [7 8]]


## array() vs asarray()

np.array() creates a new array and copies data by default.

np.asarray() converts an object to an array but avoids copying if it's already an array.

In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.asarray(arr1) # shallow copy
arr3 = np.asarray(arr1, dtype=float) # deep copy
print(arr2)
print(arr3)
print(arr1 is arr2)
print(arr1 is arr3)
print(arr2.base) # returns the original array
print(arr3.base) # returns None
arr2[0] = 10
print(arr1) # original array is also changed
print(arr2) # modified array is also changed
arr3[0] = 20
print(arr1) # original array is not changed
print(arr3) # modified array is only changed

[1 2 3]
[1. 2. 3.]
True
False
None
None
[10  2  3]
[10  2  3]
[10  2  3]
[20.  2.  3.]


In [59]:
print(id(arr1), id(arr2), id(arr3))

3087962497328 3087962497328 3087962153744


In [60]:
print(arr.shape)
print(arr.size)

(2, 3)
6


## Transpose
The .T in b.T stands for transpose in NumPy.

It swaps the rows and columns of a matrix.

In [61]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
print(np.vstack((a,b)))
print(np.hstack((a,b.T)))

b = np.array([[5,6], [7,8]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## What is the difference between ravel() and flatten()?

.ravel() returns a view (changes affect the original array).

.flatten() returns a copy (independent array).

In [62]:
arr = np.array([[1,2], [3,4]])
newarr = arr.ravel()
newarr1 = arr.flatten()
print(newarr)
print(newarr1)
print(newarr.base) 
print(newarr1.base)
newarr[0] = 10
print(arr)
print(newarr)
newarr1[0] = 20
print(arr)
print(newarr1)

[1 2 3 4]
[1 2 3 4]
[[1 2]
 [3 4]]
None
[[10  2]
 [ 3  4]]
[10  2  3  4]
[[10  2]
 [ 3  4]]
[20  2  3  4]


## nonzero element


In [63]:
arr = np.array([1,5,0,0,9])
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


## dot operation in matrices

In [64]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print(dot_product)

[[19 22]
 [43 50]]


## swapaxes() - interchanging two axes

In [65]:
arr = np.array([[1, 2], [3, 4]])
print(arr.T)
swapped = arr.swapaxes(0, 1)
print(swapped)
# print(np.swapaxes([1,2,3,4], 0, 1))
print(np.swapaxes([[1,2,3,4]], 0 , 1))  
print(np.swapaxes([[1,2,3,4]],1,0))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


## add zero arount the border of the array

In [66]:
arr0 = np.ones((4,4), dtype=int)
print(arr0)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [67]:
transformed_array = np.pad(arr0, pad_width=1, mode='constant', constant_values=0)
print(transformed_array)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


## pad() - np.pad(array, pad_width, mode='constant', constant_values=0)

pad_width: Number of values padded to the edges (can be int or tuple)

mode: How to pad ('constant', 'edge', 'reflect', 'symmetric', etc.)

constant_values: (Only used in 'constant' mode)
  
Padding arrays in NumPy is super useful when you want to:

Add borders (e.g., for image processing)

Resize arrays

Align arrays for broadcasting

In [68]:
ar = np.array([1,2,3,4,5,6])
padded = np.pad(ar, pad_width=2, mode='constant', constant_values=0)
print(padded)

padded = np.pad(ar, pad_width=2, mode='edge')
print(padded)

padded = np.pad(ar, pad_width=2, mode='reflect')
print(padded)

padded = np.pad(ar, pad_width=2, mode='symmetric')
print(padded)

[0 0 1 2 3 4 5 6 0 0]
[1 1 1 2 3 4 5 6 6 6]
[3 2 1 2 3 4 5 6 5 4]
[2 1 1 2 3 4 5 6 6 5]


In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)

padded = np.pad(arr, pad_width=1, mode='edge')
print(padded)

padded = np.pad(arr, pad_width=2, mode='reflect')
print(padded)

padded = np.pad(arr, pad_width=1, mode='symmetric')
print(padded)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]
[[3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]]
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]


In [70]:
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 1 2 0]
  [0 3 4 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 5 6 0]
  [0 7 8 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [71]:
arr = np.array([[1, 2], [3, 4]])
padded = np.pad(arr, pad_width=((1, 2), (2, 1)), mode='constant', constant_values=9)
print(padded)


[[9 9 9 9 9]
 [9 9 1 2 9]
 [9 9 3 4 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


## repeat char 5 times in an array

In [72]:
arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)
print(arr)

['i' 'love' 'NumPy' 'AND' 'interviewbit']


In [73]:
str_arr = np.repeat(arr, 5)
print(str_arr)

['i' 'i' 'i' 'i' 'i' 'love' 'love' 'love' 'love' 'love' 'NumPy' 'NumPy'
 'NumPy' 'NumPy' 'NumPy' 'AND' 'AND' 'AND' 'AND' 'AND' 'interviewbit'
 'interviewbit' 'interviewbit' 'interviewbit' 'interviewbit']


## for inserting space b/w array

In [74]:
space_arr = np.char.join(" ", arr)
print(space_arr)

['i' 'l o v e' 'N u m P y' 'A N D' 'i n t e r v i e w b i t']


## String operations

In [75]:
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))
print(np.char.capitalize(arr))
print(np.char.swapcase(arr))
print(np.char.center(arr, 20, fillchar="*"))
print(np.char.ljust(arr, 20, fillchar="*"))
print(np.char.rjust(arr, 20, fillchar="*"))
print(np.char.lstrip(arr, 'i'))

['I' 'LOVE' 'NUMPY' 'AND' 'INTERVIEWBIT']
['i' 'love' 'numpy' 'and' 'interviewbit']
['I' 'Love' 'Numpy' 'And' 'Interviewbit']
['I' 'Love' 'Numpy' 'And' 'Interviewbit']
['I' 'LOVE' 'nUMpY' 'and' 'INTERVIEWBIT']
['*********i**********' '********love********' '*******NumPy********'
 '********AND*********' '****interviewbit****']
['i*******************' 'love****************' 'NumPy***************'
 'AND*****************' 'interviewbit********']
['*******************i' '****************love' '***************NumPy'
 '*****************AND' '********interviewbit']
['' 'love' 'NumPy' 'AND' 'nterviewbit']


In [76]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7])
c = np.array([8, 9, 10, 11, 12])
p, q, r = np.ix_(a, b, c)
print(p)
print(q)
print(r)

[[[1]]

 [[2]]

 [[3]]

 [[4]]]
[[[5]
  [6]
  [7]]]
[[[ 8  9 10 11 12]]]


In [77]:
a = np.array([(1,2,50)])

print(a.itemsize)

4


In [78]:
fives = np.ones(5)
print(fives)
print(fives.itemsize)

[1. 1. 1. 1. 1.]
8


In [79]:
fives[3] = 200
print(fives)

[  1.   1.   1. 200.   1.]


## The main difference is that array will make a copy of the original data and using different object we can modify the data in the original array.



In [80]:
np.array(fives)[1] = 100
print(fives)

[  1.   1.   1. 200.   1.]


In [81]:
np.asarray(fives)[1] = 100
print(fives)

[  1. 100.   1. 200.   1.]


In [82]:
np_fives = np.array(fives)
fives is np_fives

False

In [83]:
as_fives = np.asarray(fives)
fives is as_fives

True

## How do you save and load a NumPy array to/from a file?

save a single array with .npy

save multiple array with .npz and savez()

In [84]:
np.save('fives', fives)

# load single array from file
load_arr  = np.load('fives.npy')
print(load_arr)

[  1. 100.   1. 200.   1.]


In [85]:
np.savez("my_arrays.npz", arr1=fives, arr2=np_fives)

# load multiple arrays from file
load_dict = np.load("my_arrays.npz")
print(load_dict['arr1'])
print(load_dict['arr2'])


[  1. 100.   1. 200.   1.]
[  1. 100.   1. 200.   1.]


In [86]:
# save as text file
np.savetxt('fives.txt', fives, delimiter=',', fmt="%d")

# load text file
load_arr = np.loadtxt('fives.txt', delimiter=',')
print(load_arr)

[  1. 100.   1. 200.   1.]


## How to Normalize a NumPy Array to the [0, 1] Range
Normalization is the process of scaling the values of an array so that they fall within a specific range—typically [0, 1]. This is commonly used in data preprocessing for machine learning, image processing, etc.



In [87]:
arr = np.array([10,20,30,40,50])
normalized_arr = (arr - min(arr)) / (max(arr) - min(arr))
print(normalized_arr)

[0.   0.25 0.5  0.75 1.  ]


## np.vectorise()

In [88]:
def custom_fuc(x):
    return x**2 + 1

vectorized_fuc = np.vectorize(custom_fuc)

arr = np.array([1, 2, 3, 4, 5])
result = vectorized_fuc(arr)
print(result)

[ 2  5 10 17 26]


In [89]:
def classify(x):
    return 'even' if x % 2 == 0 else 'odd'

arr = np.array([1, 2, 3, 4, 5])
result = np.vectorize(classify)(arr)
print(result)

['odd' 'even' 'odd' 'even' 'odd']


## How do you compute the outer product of two vectors?

In [90]:
print(np.outer([1, 2, 3], [4, 5, 6]))
print(np.outer([1, 2, 3], 4))
print(np.outer(4, [1, 2, 3]))
print(np.outer(4, 5))
print(np.outer([1, 2, 3], [4, 5, 6, 7]))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4]
 [ 8]
 [12]]
[[ 4  8 12]]
[[20]]
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


## How do you measure the execution time of a NumPy operation?

In [91]:
import time
start = time.time()
result = np.dot([[1, 2], [3, 4]], [[5, 6], [7, 8]])
end = time.time()
print(end - start)



0.0


In [92]:
start = time.time()
def sqaure(x):
    return x**2
arr = np.array([1, 2, 3, 4, 5])
result = list(map(sqaure, arr))
print(result)
end = time.time()
print(end - start)

[1, 4, 9, 16, 25]
0.0


In [93]:
start = time.time()
result = np.power(arr, 2)
print(result)
end = time.time()
print(end - start)

[ 1  4  9 16 25]
0.0


## Swap arrays

In [94]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[[0,2]] = arr[[2,0]]
print(arr)

[[5 6]
 [3 4]
 [1 2]]


## Given a 2D array, how do you replace all rows with their mean?

In [95]:
arr = np.array([1, 2, 3, 4, 5])
arr[:] = np.mean(arr)
print(arr)

[3 3 3 3 3]


In [96]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[:] = np.mean(arr, axis=1, keepdims=True)
print(arr)

[[1 1]
 [3 3]
 [5 5]]


In [97]:
print(np.mean([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(np.mean([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], axis=1))
print(np.mean([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], axis=0))
print(np.mean([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], axis=2))

4.5
[[2. 3.]
 [6. 7.]]
[[3. 4.]
 [5. 6.]]
[[1.5 3.5]
 [5.5 7.5]]


## How do you count occurrences of each value in an array?

In [98]:
print(np.bincount([1,1,2,1,2,3,3,4,3]))
# this prints the frequency of each number in the array starting from 0 to 4
# 0 → 0 times

# 1 → 3 times

# 2 → 2 times

# 3 → 3 times

# 4 → 1 time

[0 3 2 3 1]


## lexsort() - Sorts arrays based on multiple keys:

In [99]:
name = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
ages = np.array([21, 19, 19, 20, 20, 21, 20])
idx = np.lexsort((name,ages)) # first will sort by name and then by age
print(idx)
print(name[idx])
print(ages[idx])
new_arr = [[name[i], ages[i]] for i in idx]
print(new_arr)

[1 2 3 6 4 0 5]
['Joe' 'Will' 'Bob' 'Joe' 'Will' 'Bob' 'Joe']
[19 19 20 20 20 21 21]
[['Joe', 19], ['Will', 19], ['Bob', 20], ['Joe', 20], ['Will', 20], ['Bob', 21], ['Joe', 21]]


## How does NumPy handle division by zero?

In [100]:
arr = np.array([1, 2, 0, -1, 5])
result = np.array([2,3,4, 3, 1]) / arr
print(result)

[ 2.   1.5  inf -3.   0.2]


C:\Users\Drashti Trivedi\AppData\Local\Temp\ipykernel_24476\3407500405.py:2: RuntimeWarning: divide by zero encountered in divide
  result = np.array([2,3,4, 3, 1]) / arr


## What is the output of np.array([1, 2, 3], dtype=np.float32) * np.array([1, 2, 3], dtype=np.int32)?

In [101]:
arr = np.array([1, 2, 0, -1, 5])
flaot_arr = np.array([2.0, 3.0, 4.0, 3.0, 1.0])
print(arr * flaot_arr)

[ 2.  6.  0. -3.  5.]


## How do you handle non-finite values (inf, nan) in an array?

In [102]:
arr = np.array([1, np.inf, np.nan, 2, 1])
cleaned = arr[np.isfinite(arr)] 
print(cleaned)

[1. 2. 1.]


In [103]:
print(np.linspace(1,20,6,dtype=int))
print(np.arange(1,20,2,dtype=int))

[ 1  4  8 12 16 20]
[ 1  3  5  7  9 11 13 15 17 19]


## asarray vs array

### np.array(arr1):

Always creates a new copy of the data, unless you pass copy=False explicitly.

So arr2 is not the same object as arr1.

### np.asarray(arr1):

Avoids copying if arr1 is already a NumPy array.

It returns the original array if no copy is needed.

So arr3 is the same object as arr1.

In [104]:
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
asarr = np.asarray(list1)
print(arr)
print(asarr)
print(type(arr))
print(type(asarr))
arr[0] = 10
print(arr)
asarr[0] = 10
print(asarr)
print(asarr is arr)

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array(arr1)
arr3 = np.asarray(arr1) 

print(arr1 is arr2)
print(arr1 is arr3)


[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[10  2  3  4  5]
[10  2  3  4  5]
False
False
True


In [105]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]) 
print(arr.shape)
arr1 = np.array([1,10,100])
print(arr1.shape)
print(arr + arr1)

(2, 2, 3)
(3,)
[[[  2  12 103]
  [  5  15 106]]

 [[  8  18 109]
  [ 11  21 112]]]


In [106]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr1 = arr[1:4] # slicing is a view
print(arr1)
print(arr1 is arr)
print(arr1.base is arr)
arr1[0] = 10
print(arr1)
print(arr)
print(arr1.base) 


[1 2 3 4 5]
[2 3 4]
False
True
[10  3  4]
[ 1 10  3  4  5]
[ 1 10  3  4  5]


## share_memory()

In [107]:
print(np.shares_memory(arr, arr1))

True


### reverse 2d array

In [108]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[::-1,:]) # reverse rows and same as arr_2d[::-1]
print(arr_2d[:,::-1]) # reverse columns and same as arr_2d[:,::-1]
print(arr_2d[::-1,::-1]) # reverse both rows and columns
print(arr_2d.T) # transpose

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## np.flip()

In [109]:
print(np.flip(np.array([1, 2, 3, 4, 5])))
print(np.flip(arr_2d)) # reverse rows and columns
print(np.flip(arr_2d, axis=0)) # reverse rows
print(np.flip(arr_2d, axis=1)) # reverse columns
print(np.flip(arr_2d, axis=-1)) # reverse columns

[5 4 3 2 1]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


## Boolean indexing

In [110]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask) # This will return a boolean array
print(arr[mask]) # This will return a new array containing only the elements that are True in the mask
print(arr[arr > 3]) # This will also return a new array containing only the elements that are True in the mask

[False False False  True  True]
[4 5]
[4 5]


In [111]:
print(np.where(arr > 3)) # This will return a tuple containing the indices of the elements that are True in the mask
print(arr[np.where(arr > 3)]) # This will return a new array containing only the elements that are True in the mask

(array([3, 4], dtype=int64),)
[4 5]


In [112]:
print(arr_2d)
print(arr_2d[:,0])
print(arr_2d[0,:])

print(arr_2d[[0],:])
print(arr_2d[:,[0]])
print(arr_2d[:,[0,2]])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]
[[1 2 3]]
[[1]
 [4]
 [7]]
[[1 3]
 [4 6]
 [7 9]]


## Code	Meaning

np.where(condition, x, y)	Element-wise conditional (ternary op)

np.where(condition)	Returns indices where condition is True

arr[condition]	Filters array using boolean mask

arr[np.where(condition)]	Same as above (returns filtered values)

arr[np.where(condition, x, y)]	❌ Invalid indexing — gives wrong result

In [113]:
arr1 = arr[np.where(arr > 3)]
print(arr1)
print(arr1 is arr)
arr2 = arr[arr > 3]
print(arr2)
print(arr2 is arr)
arr3 = np.where(arr > 3, True, False)
print(arr3)
print(arr3 is arr)

# arr2[0] = 10
# print(arr2)
# print(arr)

[4 5]
False
[4 5]
False
[False False False  True  True]
False


In [114]:
print(np.arange(10)[::2])
print(np.arange(10)[1::2])
print(np.arange(10)[::-1])
print(np.arange(10)[::-2])

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]


## Percentile

In [115]:
print(arr)
print(np.percentile(arr, 50))
print(np.percentile(arr, [25, 50, 75]))
print(np.percentile(arr, [25, 50, 75], interpolation='nearest'))
print(np.percentile(arr, [25, 50, 75], interpolation='midpoint'))
print(np.percentile(arr, [25, 50, 75], interpolation='linear'))

[1 2 3 4 5]
3.0
[2. 3. 4.]
[2 3 4]
[2. 3. 4.]
[2. 3. 4.]


In [116]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])

# Compute 50th percentile along rows (axis=0)
# ➡ For each column, compute the 50th percentile (which is the median).
# Columns:

# 1st column: [10, 40] → median = 25

# 2nd column: [20, 50] → median = 35

# 3rd column: [30, 60] → median = 45
p50_cols = np.percentile(arr_2d, 50, axis=0)  # [25. 35. 45.]

# Compute 50th percentile along columns (axis=1)
# For each row, compute the 50th percentile (median).

# Rows:

# 1st row: [10, 20, 30] → median = 20

# 2nd row: [40, 50, 60] → median = 50
p50_rows = np.percentile(arr_2d, 50, axis=1)  # [20. 50.]

print(p50_cols, p50_rows)

[25. 35. 45.] [20. 50.]


## var() and std()

In [117]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

var = np.var(arr)
std = np.std(arr)

print("Variance:", var)  # Output: 2.0
print("Standard Deviation:", std)  # Output: 1.4142...

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

var_2d = np.var(arr_2d, axis=0)
std_2d = np.std(arr_2d, axis=1)

print("Variance along rows:", var_2d)  # Output: [1. 1.]
print("Standard Deviation along columns:", std_2d)  # Output: [1.4142... 1.4142...]

Variance: 2.0
Standard Deviation: 1.4142135623730951
Variance along rows: [2.25 2.25 2.25]
Standard Deviation along columns: [0.81649658 0.81649658]


## correlation coefficient - np.corrcoef(x,y)

corr_matrix[0, 1] or corr_matrix[1, 0] gives the correlation coefficient between x and y.

Value will be between -1 and 1:

1: Perfect positive correlation

0: No correlation

-1: Perfect negative correlation

In [118]:


x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

corr_matrix = np.corrcoef(x, y)
print(corr_matrix)


[[1. 1.]
 [1. 1.]]


In [119]:
arr = np.array([[1, 2, 3], [10, 20, 30]])
print(np.corrcoef(arr))


[[1. 1.]
 [1. 1.]]


In [120]:
np.corrcoef(arr.T)


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:


arr = np.array([
    [1,  2,  3,  4],    # Variable A (increasing)
    [2,  4,  6,  9],    # Variable B (roughly 2×A, but not perfectly)
    [10, 8,  6,  4]     # Variable C (decreasing, negatively correlated with A)
])

# Correlation between variables (rows)
print(np.corrcoef(arr))


[[ 1.          0.99437671 -1.        ]
 [ 0.99437671  1.         -0.99437671]
 [-1.         -0.99437671  1.        ]]


## Python vs Numpy

In [122]:
import time

# Pure Python
start = time.time()
arr1 = [i for i in range(1000000)]
arr2 = [i for i in range(1000000)]
result = [a + b for a, b in zip(arr1, arr2)]
end = time.time()
print(f"Pure Python time: {end - start}")

# NumPy
start = time.time()
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
result = arr1 + arr2  # Vectorized operation
end = time.time()
print(f"NumPy time: {end - start}")


Pure Python time: 0.2300434112548828
NumPy time: 0.043265581130981445


## strides

In [123]:
arr = np.array([1,2,3,4,5])
print(arr.strides)

arr = np.array([[1,2,3,4,5]])
print(arr.strides)

arr = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr.strides)

arr = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print(arr.strides)

(4,)
(20, 4)
(20, 4)
(20, 4)


In [124]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)
print(arr_3d.strides)

arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(arr_4d)
print(arr_4d.strides)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(16, 8, 4)
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(32, 16, 8, 4)


## Memory size of array

In [125]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Check the memory size using .nbytes
print(f"Memory size of arr: {arr.nbytes} bytes")

print(arr.size, arr.itemsize)

# Alternatively, calculate manually
print(f"Manual memory size calculation: {arr.size * arr.itemsize} bytes")

Memory size of arr: 20 bytes
5 4
Manual memory size calculation: 20 bytes


## in place operations

In-place operations in NumPy are extremely efficient for both memory usage and performance, especially when working with large arrays or performing repeated computations. They avoid unnecessary data copying, reduce memory overhead, and speed up computations, making them a key tool when optimizing numerical and scientific computations.

In [126]:
arr = np.array([1, 2, 3, 4, 5])
arr += 5
print(arr)

arr -= 5
print(arr)

arr *= 2
print(arr)

# arr %= 2
# print(arr)

np.sort(arr, axis=0, kind='quicksort')
print(arr)

[ 6  7  8  9 10]
[1 2 3 4 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [127]:
arr = np.array([1.5, 2.5, 3.5], dtype=np.float64)  # 8 bytes per element
print(arr.itemsize)
arr = arr.astype(np.float32)  # Downcast to 4 bytes per element
print(arr.itemsize)


8
4


Slicing and reshaping often result in views of the original array, maintaining similar strides.

Transposing modifies the strides to match the new memory layout after swapping axes.

Fancy and boolean indexing can change the strides since the selected elements may no longer be contiguous in memory.

In [128]:
import numpy as np

# Create a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Print strides
print("Original array strides:", arr.strides)

# Slice the array
sliced_arr = arr[:, 1]  # Taking all rows and only the second column
print(sliced_arr)
print("Sliced array strides:", sliced_arr.strides)

# Reshape the array
reshaped_arr = arr.reshape(3, 2)
print("Reshaped array strides:", reshaped_arr.strides)

# Transpose the array
transposed_arr = arr.T
print("Transposed array strides:", transposed_arr.strides)


Original array strides: (12, 4)
[2 5]
Sliced array strides: (12,)
Reshaped array strides: (8, 4)
Transposed array strides: (4, 12)


In [129]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.strides)

arr1 = arr[: , 0:2]
print(arr1)
print(arr1.strides)

arr2 = arr.reshape(3,2)
print(arr2)
print(arr2.strides)

arr3 = arr.T
print(arr3)
print(arr3.strides)

(12, 4)
[[1 2]
 [4 5]]
(12, 4)
[[1 2]
 [3 4]
 [5 6]]
(8, 4)
[[1 4]
 [2 5]
 [3 6]]
(4, 12)


## Record array in numpy

In [130]:

# Define a structured data type with names for each field
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4'), ('weight', 'f4')]

data = np.array([('Alice', 25, 1.7, 60), ('Bob', 30, 1.8, 70), ('Charlie', 35, 1.9, 80)], dtype=dtype)
print(data)

# convert to recarray
rec_data = data.view(np.recarray)
print(rec_data)

# accessing fields using dot notation
print(rec_data.name)
print(rec_data.age)
print(rec_data.height)
print(rec_data.weight)

# accessing fields using indexing
print(data['name'])
print(data['age'])
print(data['height'])
print(data['weight'])

# accessing fields using indexing
print(rec_data['name'])
print(rec_data['age'])
print(rec_data['height'])
print(rec_data['weight'])

# accessing fields using indexing
print(data[['name', 'age', 'height', 'weight']])

# accessing fields using slicing
print(data[:2])

# modifying fields
rec_data['height'] *= 2
print(rec_data)

rec_data.name[0] = "John"
print(rec_data)
print(rec_data[1])

[('Alice', 25, 1.7, 60.) ('Bob', 30, 1.8, 70.) ('Charlie', 35, 1.9, 80.)]
[('Alice', 25, 1.7, 60.) ('Bob', 30, 1.8, 70.) ('Charlie', 35, 1.9, 80.)]
['Alice' 'Bob' 'Charlie']
[25 30 35]
[1.7 1.8 1.9]
[60. 70. 80.]
['Alice' 'Bob' 'Charlie']
[25 30 35]
[1.7 1.8 1.9]
[60. 70. 80.]
['Alice' 'Bob' 'Charlie']
[25 30 35]
[1.7 1.8 1.9]
[60. 70. 80.]
[('Alice', 25, 1.7, 60.) ('Bob', 30, 1.8, 70.) ('Charlie', 35, 1.9, 80.)]
[('Alice', 25, 1.7, 60.) ('Bob', 30, 1.8, 70.)]
[('Alice', 25, 3.4, 60.) ('Bob', 30, 3.6, 70.) ('Charlie', 35, 3.8, 80.)]
[('John', 25, 3.4, 60.) ('Bob', 30, 3.6, 70.) ('Charlie', 35, 3.8, 80.)]
('Bob', 30, 3.6, 70.)


## Creating masked array

A masked array in NumPy is a type of array where some of its elements are masked, meaning they are marked as invalid or missing. You can "mask" elements in the array using a condition (e.g., setting specific elements to be ignored during operations). This allows you to handle missing or invalid data in your analysis without having to modify the original array or remove the values entirely.

Masked arrays are part of the numpy.ma module, which provides tools for working with arrays containing missing or invalid data.

In [131]:
arr = np.array([1,2,3,-1,-2,4,5])

# create a mask where the values are less than 0
mask = arr < 0

masked_arr = np.ma.masked_array(arr, mask=mask)

print(masked_arr)

masked_mean = np.ma.mean(masked_arr)

print(masked_mean)

masked_arr1 = np.ma.masked_where(arr < 3, arr)

print(masked_arr1)
print(np.where(arr < 3)) # This will return a tuple containing the indices of the elements that are True in the mask



[1 2 3 -- -- 4 5]
3.0
[-- -- 3 -- -- 4 5]
(array([0, 1, 3, 4], dtype=int64),)


In [132]:
arr_2d = np.array([[1, 2, 3], [4, -1, 6], [7, -2, 9]])

mask = arr_2d < 0

masked_arr = np.ma.masked_array(arr_2d, mask=mask)
# this will mask the negative values
print(masked_arr)

[[1 2 3]
 [4 -- 6]
 [7 -- 9]]


## identity matrix using eye() and identity()

In [133]:
identity_matrix = np.eye(3)
print(identity_matrix)

identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## np.convolve() - np.convolve(a, v, mode='full')

It slides one array (called a kernel or filter) across another and computes the dot product at each position.

a: Input array (like your signal or data)

v: The kernel or filter (usually small, like a window)

mode:

'full' → returns the full convolution (default)

'same' → output is the same length as a

'valid' → only includes values where v fully overlaps with a

In [134]:
arr = np.array([1, 2, 3, 4, 5])
kernal = np.ones(3) / 3
result = np.convolve(arr, kernal)
print(result)

result = np.convolve(arr, kernal, mode='valid')
print(result)

result = np.convolve(arr, kernal, mode='full')
print(result)

result = np.convolve(arr, kernal, mode='same')
print(result)

[0.33333333 1.         2.         3.         4.         3.
 1.66666667]
[2. 3. 4.]
[0.33333333 1.         2.         3.         4.         3.
 1.66666667]
[1. 2. 3. 4. 3.]


In [135]:
arr = np.random.randint(1, 10, (3, 3))
print(arr)

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[[1 8 5]
 [9 9 5]
 [1 6 2]]
[[0.    0.875 0.5  ]
 [1.    1.    0.5  ]
 [0.    0.625 0.125]]


In [136]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
odd_idx = arr % 2 != 0
odd_arr = arr[odd_idx]
print(odd_arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [137]:
outer = np.outer(arr1, arr2)
print(arr1)
print(arr2)
print(outer)

[[1 2]
 [4 5]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]]


Outer Product: The outer product produces a matrix by multiplying every element of the first vector with every element of the second vector. This gives you a 2D matrix, which can be quite useful in various scenarios like feature transformations.


Dot Product: The dot product, on the other hand, takes two vectors of the same size and returns a single number. It’s the sum of the products of corresponding elements in the vectors. So, instead of expanding into a matrix, the result is just a scalar value

In [138]:
a = np.array([1, 2])
b = np.array([3, 4])

outer_product = np.outer(a, b)
dot_product = np.dot(a, b)

print("Outer Product:\n", outer_product)
print("Dot Product:", dot_product)

Outer Product:
 [[3 4]
 [6 8]]
Dot Product: 11


## This might surprise you, but numpy.outer() only works with 1D arrays. It’s designed to compute the outer product of two vectors, not matrices. If you try to pass a 2D array, you’ll get an error.

## so np.outer(a, b) is not same as np.outer(b, a)

In [139]:
outer_product = np.outer(b, a)
print(outer_product)

[[3 6]
 [4 8]]


In [140]:
import numpy as np

# Create a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Define the threshold and the replacement value
threshold = 5
replacement_value = 0

# Replace elements greater than the threshold with the replacement value
arr[arr > threshold] = replacement_value

# Print the modified array
print(arr)


[[1 2 3]
 [4 5 0]
 [0 0 0]]


##  Identifying NaN and Infinite Values
np.isnan(): Identifies NaN values in the array.

np.isinf(): Identifies infinite values in the array.

np.isfinite(): Identifies finite values (i.e., values that are neither NaN nor infinite).

np.nanmean(): Calculates the mean of the array, ignoring NaN values.

np.nanstd(): Computes the standard deviation, ignoring NaN values.

np.nanmin() and np.nanmax(): Find the minimum or maximum values, ignoring NaN values.

np.nan_to_num(): Replaces NaN with 0, positive infinity with a large number, and negative infinity with a small number.

In [141]:
# Create an array with NaN and infinite values
arr = np.array([1, 2, np.nan, np.inf, 5])

print("Check for Nan", np.isnan(arr))
print("Check for Infinite", np.isinf(arr))
print("Check fror Finite", np.isfinite(arr))

# arr[np.isnan(arr)] = 0
arr_cleaned = np.nan_to_num(arr, nan=0, posinf=0, neginf=0)
print(arr_cleaned)

Check for Nan [False False  True False False]
Check for Infinite [False False False  True False]
Check fror Finite [ True  True False False  True]
[1. 2. 0. 0. 5.]


In [142]:
arr[np.isinf(arr)] = 4
print(arr)

arr[np.isnan(arr)] = np.nanmean(arr)
print(arr)

[ 1.  2. nan  4.  5.]
[1. 2. 3. 4. 5.]


## remove rows with any nan value

In [143]:
arr = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])
arr_cleaned = arr[~np.isnan(arr).any(axis=1)]
print(arr_cleaned)


[[1. 2. 3.]
 [7. 8. 9.]]


In [144]:
arr = np.array([[1, 2, 3], [4, np.nan, 6], [7, 8, 9]])

col_with_nan = np.isnan(arr).any(axis=0)
print(col_with_nan)

arr_cleaned = arr[:, ~col_with_nan]
print(arr_cleaned)



[False  True False]
[[1. 3.]
 [4. 6.]
 [7. 9.]]


In [145]:
arr = np.array([1,1,2,3,4,5,1,2,3,4])
print(np.unique(arr))
print(np.bincount(arr))

[1 2 3 4 5]
[0 3 2 2 2 1]


## Advanced Indexing in NumPy
Advanced indexing in NumPy allows you to select elements from an array using:

Integer arrays (fancy indexing)

Boolean masks (boolean indexing)

Unlike basic slicing (which returns views), advanced indexing always returns a copy of the data.

In [146]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # Select 1st, 3rd, and 5th elements
print(arr[indices])  # Output: [10 30 50]

[10 30 50]


In [147]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = [0, 1, 2]  # Select all rows
col_indices = [1, 0, 1]  #Select columns [1, 0, 1] for each row
print(arr[row_indices,col_indices]) # [2, 3,6]

[2 3 6]


In [148]:
arr = np.array([5, 10, 15, 20])
mask = arr > 10
print(mask) # [False, False, True, True]
print(arr[mask]) # [10,15,20]

[False False  True  True]
[15 20]


In [149]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 == 0] = -1
print(arr) # [1,-1,3,-1,5]

[ 1 -1  3 -1  5]


## Unravel_index() - Converts a flat index → (row, col)

- “If I flattened this 2D (or nD) array into 1D, what would be the original row and column of a specific element?”

np.unravel_index(flat_index, shape)
flat_index: the position in the flattened array

shape: the shape of the original multi-dimensional array

In [150]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

flat_index = 4
print(np.unravel_index(flat_index, arr.shape))

# Flattened view: [10, 20, 30, 40, 50, 60]
# Index 0 → (0,0)
# Index 1 → (0,1)
# Index 2 → (0,2)
# Index 3 → (1,0)
# Index 4 → (1,1) ✅
# Index 5 → (1,2)

(1, 1)


In [155]:
# Create a 5x5 array with 7 on the border and 0 inside
arr = np.ones((5,5), dtype=int) * 7
arr

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [157]:
arr[1:-1, 1:-1] = 0
arr

array([[7, 7, 7, 7, 7],
       [7, 0, 0, 0, 7],
       [7, 0, 0, 0, 7],
       [7, 0, 0, 0, 7],
       [7, 7, 7, 7, 7]])

In [160]:
a = np.ones((2, 3))
b = np.zeros((2, 3))
print(a, b)
v_stacked = np.vstack((a, b))
v_stacked

[[1. 1. 1.]
 [1. 1. 1.]] [[0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [162]:
h_stacked = np.hstack((a,b))
h_stacked

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])