# Basic random numbers

Summary Table

np.random.rand() -  Uniform floats in [0, 1]  -	np.random.rand(5)

np.random.uniform()	-  Custom uniform range	 -   np.random.uniform(5, 10, 5)

np.random.randint()	-  Random integers	   -     np.random.randint(0, 10, 5)

np.random.normal() -	  Gaussian distribution	  -  np.random.normal(0, 1, 1000)

np.random.choice()	-  Random samples from array -	np.random.choice([1,2,3], 2)

np.random.shuffle() -	  Shuffle array in-place -	np.random.shuffle(arr)

np.random.seed()  -	  Fix random seed	  -      np.random.seed(42)

np.random.binomial() -  Binomial distribution	 -   np.random.binomial(10, 0.5)

Key Takeaways

np.random.rand() / np.random.uniform(): For uniform random floats.

np.random.randint(): For random integers.

np.random.normal(): For Gaussian (normal) distributions.

np.random.choice(): For sampling from existing data.

np.random.seed(): Ensures reproducibility.

Modern approach: Use rng = np.random.default_rng() for better randomness control.

In [1]:
import numpy as np

## Random float

In [ ]:
rand_float = np.random.rand() # this will return random float between 0 and 1
print(rand_float)

rand_float = np.random.rand(10) # this will return 10 random floats between 0 and 1
print(rand_float)

rand_float = np.random.rand(10,5) # this will return 10x5 random floats between 0 and 1
print(rand_float) # 10 rows and 5 columns

rand_float = np.random.rand(10,5,3) # this will return 10x5x3 random floats between 0 and 1
print(rand_float) # 10 rows for first block, each block has 5 rows, each row has 3 columns

0.9418670664845257
[0.14282832 0.33441805 0.35375643 0.88231107 0.57118748 0.26549357
 0.91665462 0.71531246 0.28595168 0.10612937]
[[0.73602461 0.30161224 0.17427372 0.27497916 0.16965569]
 [0.49496649 0.85676602 0.42023072 0.90843968 0.31267381]
 [0.20528091 0.66187513 0.12677713 0.59389269 0.85996507]
 [0.98229641 0.75993151 0.54341516 0.48976973 0.77173556]
 [0.97939095 0.00332726 0.26765729 0.588089   0.50991763]
 [0.74949239 0.08370825 0.83627908 0.26973335 0.51838714]
 [0.14068646 0.63074657 0.02305814 0.26059918 0.07412484]
 [0.37105856 0.43559482 0.69215063 0.18762224 0.41002872]
 [0.4676726  0.2454504  0.92124932 0.8993542  0.39479169]
 [0.04991057 0.64140373 0.30643034 0.13742667 0.09820051]]
[[[2.26972939e-01 6.75139331e-01 3.58510784e-01]
  [6.48003114e-01 9.39178712e-01 2.24234121e-01]
  [1.92460750e-01 1.56552775e-01 2.18130375e-01]
  [9.86597499e-01 7.99644006e-01 1.53738147e-01]
  [8.24073497e-01 4.94428227e-01 5.64493467e-01]]

 [[8.67869982e-01 8.57591097e-01 7.61766

## Random integer

In [15]:
# rand_int = np.random.randint() # this throws an error because of no arguments-

rand_int_num = np.random.randint(10) # this will return random integer between 0 and 9
print(rand_int_num)

rand_int_range = np.random.randint(10,20) # this will return random integer between 10 and 19
print(rand_int_range)

rand_int_range2 = np.random.randint(10,20,5) # this will return 5 random integers between 10 and 19
print(rand_int_range2)


4
12
[19 12 13 10 12]


## Uniform

In [40]:
rand_uniform_float = np.random.uniform(low=0, high=100) # this will return random float between 0 and 100
print(rand_uniform_float)

rand_uniform_float_5 = np.random.uniform(low=0, high=100, size=5) # this will return 5 random floats between 0 and 100
print(rand_uniform_float_5)

74.76891914733896
[89.01430746 47.28797866 42.89423715 66.28457957  1.26318235]


## Choice

In [ ]:
rand_choice = np.random.choice([3, 5, 7, 9]) # this will return a random value from the list
print(rand_choice)

rand_choice = np.random.choice([3, 5, 7, 9], 5) # this will return 5 random values from the list
print(rand_choice)

rand_choice = np.random.choice([3, 5, 7, 9], 3, replace=False) # this will return 3 unique random values from the list
print(rand_choice)

7
[5 5 7 5 5]
[5 3 7]


## Shuffle - So it doesn't return a new shuffled array — it just shuffles the original one directly.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)  # In-place shuffling
print(arr)  # e.g., [3, 1, 5, 2, 4]

print(np.random.shuffle(arr)) # So it doesn't return a new shuffled array — it just shuffles the original one directly.

[5 3 2 4 1]
None


## Permutation

Returns a new shuffled copy

Does NOT modify the original array

Can work on integers too

In [83]:
permuated = np.random.permutation(arr)
print(permuated)
print(arr)
print(permuated is arr)

[1 2 3 5 4]
[1 3 2 5 4]
False


In [86]:
permuated_range = np.random.permutation(10) # this will return 10 random integers between 0 and 9
print(permuated_range)

[6 4 3 2 5 8 9 0 7 1]
