## Source https://github.com/RoyiAvital/Julia100Exercises

In [89]:
import numpy as np

In [90]:
# Create a vector with values ranging from 7 to 12
arr = np.arange(7,12,1)
print(arr)

[ 7  8  9 10 11]


In [91]:
# How to find the memory size of any array
print(arr.itemsize) # bytes per element
print(arr.nbytes) # total bytes
print(arr.itemsize * arr.nbytes) # total memory 

4
20
80


In [92]:
#  How to get the documentation of the numpy add function from the command line? (★☆☆)
# python -c "import numpy as np; help(np.add)"
#  pydoc numpy.add

In [93]:
#  Create a null vector of size 10 but the fifth value which is 1
zeros10 = np.zeros(10)
zeros10[4] = 1
print(zeros10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [94]:
# Create a vector with values ranging from 10 to 49 
v1 = np.arange(10, 49, 1)
print(v1)

# Reverse a vector (first element becomes last)
print(v1[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [95]:
# Create a 3x3 matrix with values ranging from 0 to 8
mat3 = np.arange(9).reshape(3,3)
print(mat3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [96]:
#  Find indices of non-zero elements from [1,2,0,0,4,0] 
arr = np.array([1,2,0,0,4,0])
nonzero = np.nonzero(arr)
print(nonzero)

(array([0, 1, 4], dtype=int64),)


In [97]:
#  Create a 3x3 identity matrix
mat33 = np.eye(3)
print(mat33)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
# Create a 3x3x3 array with random values (★☆☆)
arr = np.random.random((3,3,3))
print(arr)

[[[0.37796288 0.31897724 0.18001486]
  [0.80697294 0.85732671 0.67423392]
  [0.1974487  0.68811935 0.26584441]]

 [[0.06298324 0.07821962 0.58723519]
  [0.6265854  0.87537014 0.77655012]
  [0.79367469 0.42529052 0.25673065]]

 [[0.96470164 0.64095508 0.17882454]
  [0.46717425 0.22037127 0.44765164]
  [0.20105388 0.49848709 0.57245867]]]


In [99]:
#  Create a 10x10 array with random values and find the minimum and maximum values
arr10 = np.random.randint(10,size= (10,10))
print(arr10)
print(arr10.min())
print(arr10.max())

[[0 0 5 8 4 0 5 0 4 3]
 [3 6 4 1 6 0 5 6 8 9]
 [5 5 4 6 8 1 2 6 5 1]
 [8 5 9 0 4 2 2 0 3 1]
 [1 8 2 1 7 3 0 0 8 5]
 [6 5 3 3 3 4 8 8 0 9]
 [6 4 8 7 7 3 4 5 6 6]
 [9 9 6 9 2 0 6 5 0 5]
 [4 6 7 0 1 0 5 9 9 2]
 [4 9 8 8 3 3 4 6 3 4]]
0
9


In [100]:
# Create a random vector of size 30 and find the mean value
arr30 = np.random.randint(1, 101, size=(30))
print(arr30)
print(arr30.mean())

[58 36 34 69 39 46 39 85 39 28 11  6 20 36 33 18 86 95 24  3 40 79 59 61
 14  9 28 69 26  6]
39.86666666666667


In [101]:
#  Create a 2d array with 1 on the border and 0 inside
arr = np.zeros((2,2), dtype=int)
arr = np.pad(arr, pad_width=1,mode="constant", constant_values=1)

print("using np.pad()",arr)

Z = np.ones((4,4))
Z[1:-1,1:-1] = 0 # Start at index 1 (second element) and Go up to but not including the last element (-1)
print(Z)

using np.pad() [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [102]:
# What is the result of the following expression? (★☆☆)

0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False



False

In [103]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

Z = np.diag(1+np.arange(4), k=-1) 
# if above diagonal, then k = 1
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [104]:
#  Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8), dtype=int)
Z[::2,::2] = 1
Z[1::2, 1::2] = 1
# Z[::2, 1::2] = 1
Z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [105]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [106]:
# Normalize a 5x5 random matrix
arr = np.random.random((5,5))
print(arr)
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)

[[0.19179586 0.48045965 0.7092033  0.9452938  0.07912095]
 [0.63163438 0.67114653 0.36394346 0.87123936 0.517683  ]
 [0.51229065 0.12319236 0.5448486  0.82086751 0.78558303]
 [0.58099377 0.21567777 0.05944407 0.78074406 0.15271533]
 [0.10511776 0.97247179 0.44958664 0.19590998 0.74182604]]
[[0.14495922 0.46112026 0.71165335 0.97023311 0.02155125]
 [0.62669545 0.66997141 0.3335051  0.88912448 0.5018894 ]
 [0.49598338 0.06982077 0.53164271 0.83395435 0.79530878]
 [0.57123096 0.17111606 0.         0.79000887 0.10215601]
 [0.05002444 1.         0.42730639 0.14946525 0.74738363]]


In [107]:
#  If you want standard score normalization (Z-score):
Z_standardized = (arr - np.mean(arr)) / np.std(arr)
print(Z_standardized)

[[-1.0740555  -0.06845994  0.72839652  1.55084659 -1.46657229]
 [ 0.45817572  0.59582112 -0.47435828  1.29286893  0.06121218]
 [ 0.04242724 -1.31304415  0.15584683  1.11739243  0.99447463]
 [ 0.28176297 -0.99085992 -1.53511912  0.97761751 -1.21019727]
 [-1.37600922  1.64552445 -0.17600981 -1.05972343  0.84204183]]


In [108]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])

In [109]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
mat53 = np.ones((5,3))
mat32 = np.ones((3,2))

# print(mat53 * mat32) this throws an error cuz of different shape

print(mat53,mat32)
Z = np.matmul(mat53, mat32) # this works as this is matrix multiplication
Z

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [110]:
#  Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] = -1
Z

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [ ]:
# Output

# sum(range(5), -1)	9	Built-in sum() with start=-1
# from numpy import *	—	Overrides sum() with NumPy’s
# sum(range(5), -1) (NumPy)	10	NumPy sum() uses axis=-1

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10
