# numpy ufunc

## frompyfunc(function, input, output)

In [1]:
import numpy as np

def myAdd(x, y):
    return x + y

myAdd = np.frompyfunc(myAdd, 2, 1)

print(myAdd([1, 2, 3], [4, 5, 6]))



[5 7 9]


In [2]:
print(type(myAdd))

<class 'numpy.ufunc'>


In [3]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [108]:
print(np.where(type(myAdd) == np.ufunc, "yes", "no"))

yes


## Simple Arithmetic - add(), substract(), multiply(), divide(), power(), divmod(), absolute(), mod(), remainder()

In [27]:
print(np.add([1, 2, 3], [4, 5, 6]))
print(np.add([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.add(1,2))
print(np.add([1,2,2],2))
# print(np.add([1,2,3], [4,5,6], [7,8,9]))
# print(np.add([1,2,3], [4,5,6], [7,8,9], [10,11,12]))
print(np.add([1,2,3],[[4,5,6], [7,8,9]]))

[5 7 9]
[[ 6  8]
 [10 12]]
3
[3 4 4]
[[ 5  7  9]
 [ 8 10 12]]


In [20]:
print(np.subtract([1, 2, 3], [4, 5, 6]))
print(np.subtract([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.subtract(1,2))
print(np.subtract([1,2,2],2))
# print(np.subtract([1,2,3], [4,5,6], [7,8,9]))
print(np.subtract([1,2,3],[[4,5,6], [7,8,9]]))

[-3 -3 -3]
[[-4 -4]
 [-4 -4]]
-1
[-1  0  0]
[[-3 -3 -3]
 [-6 -6 -6]]


In [21]:
print(np.multiply([1, 2, 3], [4, 5, 6]))
print(np.multiply([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.multiply(1,2))
print(np.multiply([1,2,2],2))
# print(np.multiply([1,2,3], [4,5,6], [7,8,9]))
print(np.multiply([1,2,3],[[4,5,6], [7,8,9]]))

[ 4 10 18]
[[ 5 12]
 [21 32]]
2
[2 4 4]
[[ 4 10 18]
 [ 7 16 27]]


In [22]:
print(np.divide([1, 2, 3], [4, 5, 6]))
print(np.divide([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.divide(1,2))
print(np.divide([1,2,2],2))
# print(np.divide([1,2,3], [4,5,6], [7,8,9]))
print(np.divide([1,2,3],[[4,5,6], [7,8,9]]))

[0.25 0.4  0.5 ]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
0.5
[0.5 1.  1. ]
[[0.25       0.4        0.5       ]
 [0.14285714 0.25       0.33333333]]


In [26]:
print(np.power([1, 2, 3], [4, 5, 6]))
print(np.power([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.power(1,2))
print(np.power([1,2,2],2))
# print(np.power([1,2,3],[4,5,6], [7,8,9]))
print(np.power([1,2,3],[[4,5,6], [7,8,9]]))    

[  1  32 729]
[[    1    64]
 [ 2187 65536]]
1
[1 4 4]
[[    1    32   729]
 [    1   256 19683]]


In [31]:
print(np.mod([1, 2, 3], [4, 5, 6]))
print(np.mod([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.mod(1,2))
print(np.mod(10,5))

[1 2 3]
[[1 2]
 [3 4]]
1
0


In [32]:
print(np.remainder([1, 2, 3], [4, 5, 6]))
print(np.remainder([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.remainder(1,2))
print(np.remainder(10,5))

[1 2 3]
[[1 2]
 [3 4]]
1
0


In [34]:
print(np.divmod([1, 2, 3], [4, 5, 6]))
print(np.divmod([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.divmod(1,2))

(array([0, 0, 0]), array([1, 2, 3]))
(array([[0, 0],
       [0, 0]]), array([[1, 2],
       [3, 4]]))
(0, 1)


In [35]:
print(np.floor_divide([1, 2, 3], [4, 5, 6]))
print(np.floor_divide([[1, 2], [3, 4]], [[5, 6], [7, 8]]))

[0 0 0]
[[0 0]
 [0 0]]


In [36]:
print(np.true_divide([1, 2, 3], [4, 5, 6]))
print(np.true_divide([[1, 2], [3, 4]], [[5, 6], [7, 8]]))

[0.25 0.4  0.5 ]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [37]:
print(np.absolute([1, 2, 3]))
print(np.absolute([[1, 2], [3, 4]]))
print(np.absolute(1))
print(np.absolute(-1))
print(np.absolute(3+4j))
print(np.absolute(-3+4j))
print(np.absolute(3-4j))
print(np.absolute(-3-4j))

[1 2 3]
[[1 2]
 [3 4]]
1
1
5.0
5.0
5.0
5.0


## Rounding decimals = truc(), fix(), around(), ceil(), floor(),

In [42]:
print(np.trunc([1.5, 2.5, 3.5]))
print(np.trunc([[1.5, 2.5], [3.5, 4.5]]))
print(np.trunc(1.5))
print(np.trunc(-1.5))
print(np.trunc(1.9))
print(np.trunc(2.1))
print(np.trunc(2.9))


[1. 2. 3.]
[[1. 2.]
 [3. 4.]]
1.0
-1.0
1.0
2.0
2.0


In [44]:
print(np.fix([1.5, 2.5, 3.5]))
print(np.fix([[1.5, 2.5], [3.5, 4.5]]))
print(np.fix(1.5))
print(np.fix(-1.5))
print(np.fix(1.9))
print(np.fix(2.1))
print(np.fix(2.9))

[1. 2. 3.]
[[1. 2.]
 [3. 4.]]
1.0
-1.0
1.0
2.0
2.0


In [50]:
print(np.around([1.5, 2.5, 3.5]))
print(np.around(2.8))
print(np.around(2.29340953, decimals=2))
print(np.around(2.9533454, decimals=3))

[2. 2. 4.]
3.0
2.29
2.953


In [57]:
print(np.floor([1.5, 2.5, 3.5]))
print(np.floor(1.9))
print(np.floor(2.1))
print(np.floor(2.9))
print(np.floor([-3.1666, 3.6667]))
print(np.floor([-3.70, 3.70]))

[1. 2. 3.]
1.0
2.0
2.0
[-4.  3.]
[-4.  3.]


In [59]:
print(np.ceil([1.5, 2.5, 3.5]))
print(np.ceil(1.9))
print(np.ceil(2.1))
print(np.ceil(2.9))
print(np.ceil([-3.1666, 3.6667]))
print(np.ceil([-3.70, 3.70]))
print(np.ceil(1.1))

[2. 3. 4.]
2.0
3.0
3.0
[-3.  4.]
[-3.  4.]
2.0


## logs

In [60]:
arr = np.arange(10)
print(np.log2(arr))

[      -inf 0.         1.         1.5849625  2.         2.32192809
 2.5849625  2.80735492 3.         3.169925  ]


C:\Users\Drashti Trivedi\AppData\Local\Temp\ipykernel_20188\1394287963.py:2: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(arr))


In [61]:
print(np.log10(arr))

[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


C:\Users\Drashti Trivedi\AppData\Local\Temp\ipykernel_20188\1035277533.py:1: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(arr))


In [62]:
print(np.log(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Drashti Trivedi\AppData\Local\Temp\ipykernel_20188\873111080.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [63]:
from math import log

myLog = np.frompyfunc(log, 2, 1)
print(myLog(10, 100))

0.5


## Sum - add vs sum

In [ ]:
print(np.sum([1, 2, 3]))
print(np.sum([[1, 2], [3, 4]]))
print(np.sum([[1, 2], [3, 4]], axis=0)) # [[1+3, 2+4]] - column-wise
print(np.sum([[1, 2], [3, 4]], axis=1)) # [[1+2][3+4]] - row-wise
print(np.sum([[5, 1, 2], [3,2,2,]], axis=1)) # [[5+1+2], [3+2+2]] - row-wise

print(np.add([1, 2, 3], [4, 5, 6]))

6
10
[4 6]
[3 7]
[8 7]
[5 7 9]


## Cumulative sum 

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [ ]:
print(np.cumsum([1, 2, 3]))
print(np.cumsum([[1, 2], [3, 4]]))
print(np.cumsum([[1, 2], [3, 4]], axis=0)) # [[1, 2] [1+3, 2+4]] - column-wise
print(np.cumsum([[1, 2], [3, 4]], axis=1)) # [[1, 1+2][3, 3+4]] - row-wise
print(np.cumsum([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])) # flat array with sums
print(np.cumsum([[5,1,2], [3,2,2,]], axis=1)) # [[5, 5+1, 5+1+2], [3, 3+2, 3+2+2]] - row-wise

[1 3 6]
[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]
[ 1  3  6 10 15 21 28 36]
[[5 6 8]
 [3 5 7]]


## prod

In [75]:
print(np.prod([1, 2, 3]))
print(np.prod([[1, 2], [3, 4]]))
print(np.prod([[1, 2], [3, 4]], axis=0)) # [[1*3, 2*4]] - column-wise
print(np.prod([[1, 2], [3, 4]], axis=1)) # [[1*2][3*4]] - row-wise
print(np.prod([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])) # flat array with products
print(np.prod([[5,1,2], [3,2,2,]], axis=1)) # [[5*1*2], [3*2*2]] - row-wise

6
24
[3 8]
[ 2 12]
40320
[10 12]


## Cumulative product - cumprod

In [79]:
print(np.cumprod([1, 2, 3]))
print(np.cumprod([[1, 2], [3, 4]]))
print(np.cumprod([[1, 2], [3, 4]], axis=0)) # [[1, 2] [1*3, 2*4]] - column-wise
print(np.cumprod([[1, 2], [3, 4]], axis=1)) # [[1, 1*2][3, 3*4]] - row-wise
print(np.cumprod([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])) # flat array with products
print(np.cumprod([[5,1,2], [3,2,2,]], axis=1)) # [[5, 5*1, 5*1*2], [3, 3*2, 3*2*2]] - row-wise

[1 2 6]
[ 1  2  6 24]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
[    1     2     6    24   120   720  5040 40320]
[[ 5  5 10]
 [ 3  6 12]]


## differences

In [84]:
print(np.diff([1, 2, 3]))
print(np.diff([[1, 2], [3, 4]]))
print(np.diff([[1, 2], [3, 4]], axis=0)) # [[1-3, 2-4]] - column-wise
print(np.diff([[1, 2], [3, 4]], axis=1)) # [[1-2][3-4]] - row-wise
print(np.diff([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])) 
print(np.diff([[5,1,2], [3,2,2,]], axis=1)) # [[5-1-2], [3-2-2]] - row-wise
print(np.diff([1,2,3,4], n=2))
print(np.diff([3,4,5,6], n=2))
print(np.diff([10,20,30], n=2))

[1 1]
[[1]
 [1]]
[[2 2]]
[[1]
 [1]]
[[[1]
  [1]]

 [[1]
  [1]]]
[[-4  1]
 [-1  0]]
[0 0]
[0 0]
[0]


## LCM

In [90]:
print(np.lcm([1, 2, 3], [4, 5, 6]))
print(np.lcm([[1, 2], [3, 4]], [[5, 6], [7, 8]]))
print(np.lcm(1,2))
print(np.lcm(10,5))
print(np.lcm.reduce([3,6,9]))

[ 4 10  6]
[[ 5  6]
 [21  8]]
2
10
18


## GCD


In [94]:
print(np.gcd(10,190))
print(np.gcd.reduce([10,190,30]))


10
10


## Set operations

In [96]:
print(np.unique([1,1,1,2,3,4,2,3,4,5]))
print(np.unique([1,1,1,2,3,4,2,3,4,5], return_counts=True))


[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([3, 2, 2, 2, 1], dtype=int64))


In [102]:
print(np.union1d([1,2,3], [4,5,6]))
print(np.intersect1d([1,2,3], [4,5,6]))
print(np.union1d([1,2,3,4,5], [2,3,4,5,6]))
print(np.intersect1d([1,2,3,4,5], [2,3,4,5,6]))
print(np.intersect1d([1,2,3,4,5], [2,3,4,5,6], assume_unique=True))

[1 2 3 4 5 6]
[]
[1 2 3 4 5 6]
[2 3 4 5]
[2 3 4 5]


## setdiff1d - To find only the values in the first set that is NOT present in the seconds set

## setxor1d - To find only the values that are NOT present in BOTH sets

In [104]:
print(np.setdiff1d([1,2,3,4,5], [2,3,4,5,6], assume_unique=True))
print(np.setxor1d([1,2,3,4,5], [2,3,4,5,6], assume_unique=True))

[1]
[1 6]


## mean, median and standard deviation

In [107]:
arr = np.array([1,2,3,4,5])

print(arr.mean())
print(arr.std())
print(np.median(arr))
print(np.percentile(arr, 50))


3.0
1.4142135623730951
3.0
3.0


## Mean Squared Error

In [ ]:
# 1. We have two arrays, our prediction, and actual labels
# 2. We take the squared differences and sum them
# 3. We then divide by n, which is the length of the array

n= len(labels)
error = (1/n) * np.sum(np.square(predictions - labels))

## arr[:,0] vs arr[:,[0]] 

In [110]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
new_arr = arr[:,0]
print(new_arr)

[1 6]


In [111]:
new_arr1 = arr[0,:]
print(new_arr1)

[1 2 3 4 5]


In [112]:
new_arr2 = arr[:,[0]]
print(new_arr2)

[[1]
 [6]]


## bincount()

In [ ]:
print(np.bincount([1,1,2,3,4,5,1,0,0])) # 0 -> 2, 1 -> 3, 2 -> 1, 3 -> 1, 4 -> 1, 5 -> 1

[2 3 1 1 1 1]


## mean() vs average()

In [ ]:
print(np.mean([1,2,3,4,5]))
print(np.average([1,2,3,4,5]))


3.0
3.0
