In [1]:
import numpy as np

## Practice

In [ ]:
a = [1,2,3,4]
arr = np.array(a)
arr

array([1., 2., 3., 4.])

In [13]:
print(np.ones(3, dtype=int))
print(np.ones(3))
print(np.ones((2,3), dtype=int))
print(np.ones((2,2)))

[1 1 1]
[1. 1. 1.]
[[1 1 1]
 [1 1 1]]
[[1. 1.]
 [1. 1.]]


In [15]:
print(np.eye(3))
print(np.eye(3,1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.]
 [0.]
 [0.]]


In [17]:
print(np.eye(3,3))
print(np.eye(3,3,1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [18]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [21]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
print(a, c)
# np.dot(a, c).shape
# np.matmul(a, c).shape
# n is 7, k is 4, m is 3

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   ...
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]


In [28]:
arr = np.array([3,4,5,7])
print(np.min(arr))
print(np.min(arr,axis=0))
# print(np.min(arr,axis=1))

3
3


In [26]:
arr1 = np.array([[1,2,3,5], [4,2,5,6]])
print(np.min(arr1))
print(np.min(arr1, axis=0))
print(np.min(arr1, axis=1))

1
[1 2 3 5]
[1 2]


In [40]:
np.random.seed(10)
print(np.random.randint(1,19,3))

[10  5 16]


In [50]:
import random

a = list(range(10))  # Sample dataset
random.seed(10)
random.shuffle(a)
print(a)  # The order will always be the same when using seed


[5, 2, 7, 1, 8, 4, 3, 6, 0, 9]
